version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    restart: always
#    tty: true

  server:
    build: ./marche-realtime-coffee-server/
    ports:
      - 3000:3000