name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: almerindo/action-env-from-aws-ssm@v1.2.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MY_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        with:
          ssm-path: /app-nestjs
          format: shell
          output: .env
          decryption: true

          
      - name: List directory
        run: ls -la
      
      - run: |
          cat .env
      
      # - uses: ProcureAi/aws-ssm-secrets-multiple@v1.0.0
      #   with:
      #     SSM_PARAMETERS: |
      #       PARAMETER=app-nestjs

      # - run: | 
      #     echo $PARAMETER > .env

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push image to Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: app-nestjs
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
