name: CI
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: ProcureAi/aws-ssm-secrets-multiple@v1.0.0
        with:
          SSM_PARAMETERS: |
            PARAMETER=test-parameter
      - run: |
          echo "this is your secret: $PARAMETER"

      - run: | 
          echo $PARAMETER > .env
          
      - name: List directory
        run: ls -la
          
      - run: |
          cat .env
      
      
      
      
      
      
      
      
